# Name of website
#title: Ben Morton

# Your name to show in the footer
author: Ben Morton

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Reddit: "https://www.reddit.com/user/benn-9833"
    - Discord server: "https://discord.gg/A4tGeWhQC3"
  Author's home: "benn9833.github.io"
